[target]
# Target binary to fuzz
path = "/path/to/instrumented/target"

# Instrumented with *SAN binary to use
san_path = "/path/to/sanitizer/target"

# Instrumented with CMPLOG binary to use
cmpl_path = "/path/to/cmplog/target"

# Instrumented with Laf-intel/CMPCOV binary to use
cmpc_path = "/path/to/cmpcov/target"

# Target binary arguments, including @@ if needed
args = ["-foo", "--bar", "baz", "@@"]

[afl_cfg]
# Amount of processes to spin up
runners = 1

# Custom path to 'afl-fuzz' binary
afl_binary = "/path/to/afl-fuzz"

# Seed corpus directory
seed_dir = "/path/to/input_dir"

# Solution/Crash output directory
solution_dir = "/path/to/output_dir"

# Token dictionary to use
dictionary = "/path/to/dictionary"

# Custom AFL flags
afl_flags = "-T 'MyFuzzer' -s 1234 -t 1000+"

# Select the mode that determines the fuzzing strategy
# Available modes: default, multiple-cores, ci-fuzzing
mode = "multiple-cores"


[session]
# Spin up a custom tmux session with the fuzzers
dry_run = false

# Custom tmux session name
name = "my_session"

# Runner backend to use: [tmux, screen]
runner = "tmux"

[misc]
# Enable TUI mode
tui = true

# Start with no tui and detached from any session
detached = false

# If specified the AFLR will attempt to create a ramdisk for fuzzing
ramdisk = false

# Provide a seed for AFLR internal PRNG to get deterministic command generation
seed = 0xdeadb33fc0ffee

# Allow feeding the seed to AFL for deterministic fuzzing campaigns
use_seed_afl = false
