[package]
name = "afl_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["wrap_help", "string", "derive"] }
rand = "0.8.5"
tmux_interface = "0.3.1"
