[package]
name = "afl_runner"
authors = ["0x434b <admin@0x434b.dev"]
repository = "https://github.com/0xricksanchez/AFL_Runner"
description = "AFL Runner is a tool to run an efficient multi-core AFLPlusPlus campaign."
version = "0.3.0"
edition = "2021"
keywords = ["afl", "fuzzing", "fuzzer", "fuzz"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["wrap_help", "string", "derive"] }
rand = "0.8.5"
sysinfo = "0.30.11"
upon = "0.8.1"
toml = "0.8.12"
serde = { version = "1.0.198", features = ["derive"] }
ratatui = { version = "0.26.2", features = ["crossterm", "all-widgets"] }
crossterm = "0.27.0"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
