[package]
name = "afl_runner"
authors = ["0x434b <admin@0x434b.dev"]
repository = "https://github.com/0xricksanchez/AFL_Runner"
description = "Scaling best-practice AFLPlusPlus fuzzing campaigns made easy"
version = "0.3.5"
edition = "2021"
keywords = [
  "afl",
  "fuzzing",
  "fuzzer",
  "fuzz",
  "afl++",
  "aflplusplus",
  "testing",
  "fuzz-testing",
  "fuzz-test",
]
license = "Apache-2.0"

[[bin]]
name = "aflr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["wrap_help", "string", "derive"] }
rand = "0.8.5"
sysinfo = "0.30.11"
upon = "0.8.1"
toml = "0.8.12"
serde = { version = "1.0.199", features = ["derive"] }
ratatui = { version = "0.26.2", features = ["crossterm", "all-widgets"] }
crossterm = "0.27.0"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
